CREATE TABLE person (
  person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personal_number VARCHAR(20) NOT NULL UNIQUE,
  first_name VARCHAR(100),
  address VARCHAR(100)
);

CREATE TABLE person_phone (
  person_id INT NOT NULL REFERENCES person(person_id),
  phone_number VARCHAR(20) NOT NULL,
  PRIMARY KEY (person_id, phone_number)
);

CREATE TABLE job_title (
  job_title_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE department (
  department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR(100) NOT NULL UNIQUE,
  manager_supervisor_id INT
);

CREATE TABLE employee (
  employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  skill_set VARCHAR(100),
  department_id INT NOT NULL REFERENCES department(department_id),
  job_title_id INT NOT NULL REFERENCES job_title(job_title_id),
  person_id INT NOT NULL REFERENCES person(person_id),
  manager_id INT REFERENCES employee(employee_id)
);

ALTER TABLE department
  ADD CONSTRAINT fk_department_manager
  FOREIGN KEY (manager_supervisor_id) REFERENCES employee(employee_id);

CREATE TABLE employee_salary (
  employee_salary_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  salary NUMERIC(10,2) NOT NULL CHECK (salary >= 0),
  valid_from DATE NOT NULL,
  valid_to DATE NULL,
  CHECK (valid_to IS NULL OR valid_to > valid_from)
);

CREATE TABLE period (
  period_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_name CHAR(2) NOT NULL UNIQUE
);

CREATE TABLE course (
  course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_name VARCHAR(100),
  course_code CHAR(6) NOT NULL UNIQUE
);

CREATE TABLE course_layout (
  course_layout_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INT NOT NULL REFERENCES course(course_id),
  min_students INT,
  max_students INT,
  hp NUMERIC(4,1)
);

CREATE TABLE course_instance (
  course_instance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  instance_id INT NOT NULL UNIQUE,
  num_students INT,
  course_layout_id INT NOT NULL REFERENCES course_layout(course_layout_id),
  period_id INT NOT NULL REFERENCES period(period_id),
  course_id INT NOT NULL REFERENCES course(course_id)
);

CREATE TABLE teaching_activity (
  teaching_activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  factor NUMERIC(4,2),
  activity_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE planned_activity (
  planned_activity_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  planned_hours INT,
  teaching_activity_id INT NOT NULL REFERENCES teaching_activity(teaching_activity_id),
  course_instance_id INT NOT NULL REFERENCES course_instance(course_instance_id)
);

CREATE TABLE work_allocation (
  employee_id INT NOT NULL REFERENCES employee(employee_id),
  planned_activity_id INT NOT NULL REFERENCES planned_activity(planned_activity_id),
  allocated_hours INT,
  PRIMARY KEY (employee_id, planned_activity_id)
);
